In [13]:
import numpy as np

In [14]:
n = int(input("Ener Marix Size: "))
A = np.zeros((n, n))
for i in range(n):
  for j in range(n):
    A[i][j] = float(input(f"A[{i}][{j}] = "))

Ener Marix Size: 3
A[0][0] = 1
A[0][1] = 1
A[0][2] = 1
A[1][0] = 0
A[1][1] = 2
A[1][2] = 2
A[2][0] = 1
A[2][1] = 1
A[2][2] = 2


In [15]:
print(A)

[[1. 1. 1.]
 [0. 2. 2.]
 [1. 1. 2.]]


**"Direct Library"**

In [16]:
if np.linalg.det(A) != 0:
  print("1-Norm = ", np.linalg.cond(A, 1))
  print("2-Norm = ", np.linalg.cond(A, 2))
  print("Infinity-Norm", np.linalg.cond(A, np.inf))
else:
  print("Matrix is Singular")

1-Norm =  15.0
2-Norm =  8.45909178002303
Infinity-Norm 10.0


**Manual Calculation**

In [17]:
A_inv = np.linalg.inv(A)

col_sum1 = []
col_sum2 = []

for j in range(n):
  sum1 = 0
  sum2 = 0
  for i in range(n):
    sum1 = sum1 + abs(A[i][j])
    sum2 = sum2 + abs(A_inv[i][j])
  col_sum1.append(sum1)
  col_sum2.append(sum2)

condA = max(col_sum1) * max(col_sum2)
condA

np.float64(15.0)

In [18]:
A_inv = np.linalg.inv(A)

row_sum1 = []
row_sum2 = []

for i in range(n):
  sum1 = 0
  sum2 = 0
  for j in range(n):
    sum1 = sum1 + abs(A[i][j])
    sum2 = sum2 + abs(A_inv[i][j])
  row_sum1.append(sum1)
  row_sum2.append(sum2)

condA = max(row_sum1) * max(row_sum2)
condA

np.float64(10.0)